### ISSUE TITLE
Not showing output even model achieved 93 % validation accuracy

### ISSUE THREAD

**Issue by Shivam412** [tucan9389/tf2-mobile-pose-estimation#15]
Hi, Thanks for the code. I trained this model with 93% accuracy but still model did not give any output.

**Comment by tucan9389** [comment]
I have same issue. It will be fixed soon.

**Comment by Shivam412** [comment]
okay good to hear it. The issue caught because of preprocessing might be, I tried many things but still not able to get outputs.

**Comment by tucan9389** [comment]
I think the accuracy metric is incorrect on this domain(pose estimation). I'm sorry for providing incorrect information and this project needs new metric calculations like `PCKh@.5`.

**Comment by tucan9389** [comment]
Sorry for reply late. 
Here is PCKh@.5 result. 
https://github.com/tucan9389/tf2-mobile-pose-estimation/issues/39

Thank you.
