### ISSUE TITLE
from_concrete_function()

### ISSUE THREAD

**Issue by yxxxqqq** [tucan9389/tf2-mobile-pose-estimation#17]
'TFLiteConverterV2' has no attribute 'from_concrete_function'?

The reason is that tensorflow2.0 has changed the function from 'from_concrete_function(func)' to 'from_concrete_function(cls,funcs)'. So we only need to change the code to 'converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])'

**Comment by tucan9389** [comment]
@Yxiaoqian 

Thanks for your suggestion. If you make the code can convert to tflite from tf2 model, you can make pull request! 👍

**Comment by tucan9389** [comment]
Please reopen the issue feel free.
