### ISSUE TITLE
How  can I get the epoch accuracy?

### ISSUE THREAD

**Issue by yxxxqqq** [tucan9389/tf2-mobile-pose-estimation#18]

**Comment by tucan9389** [comment]
@Yxiaoqian 

In this repo, not implemented yet for a benchmark.
But there are many metrics for pose estimation domain. For example:
- Percentage of Detected Joints (PDJ) 
- Object Keypoint Similarity (OKS)

You can find the way of calculation for the metrics on [here](https://nanonets.com/blog/human-pose-estimation-2d-guide/) and [here](https://medium.com/@masherov14/pose-estimation-metrics-844c07ba0a78).

**Comment by tucan9389** [comment]
@yxxxqqq 
If you have more quest about the issue, please reopen the issue.
