### ISSUE TITLE
port to tf.keras from slim 

### ISSUE THREAD

**Issue by tucan9389** [tucan9389/tf2-mobile-pose-estimation#4]

**Comment by tucan9389** [comment]
Support TF2 now.

**Comment by aitikgupta** [comment]
Hi @tucan9389, thanks a lot for your work.
Could you point me to some how-do-you-dos for such port problems?

**Comment by tucan9389** [comment]
I converted each layer manually. It’s painful works for me 😭
And then compared the ported model by using TensorFlow's graph visualization tool and https://github.com/lutzroeder/Netron

**Comment by aitikgupta** [comment]
I'd love to read some of your blog or article on this!
